### ISSUE TITLE
doesn't compile on Windows with UNICODE enabled

### ISSUE THREAD

**Issue by hmoffatt** [sryze/glob#1]
If you have UNICODE #defined, then glob.cpp doesn't compile.

You are calling FindFirstFileA (ASCII-only) with a struct of type WIN32_FIND_DATA, which is Unicode or ASCII depending on whether UNICODE is #defined or not.

If you make find_data_ of type WIN32_FIND_DATAA instead it compiles.

**Comment by sryze** [comment]
Thanks! now it's fixed🤦
