### ISSUE TITLE
eats paths

### ISSUE THREAD

**Issue by hmoffatt** [sryze/glob#2]
I would expect glob("/path/*") to return all the elements with the "/path/" prefix included, but they aren't. This is different to how glob.glob() behaves in Python for example.

**Comment by BoomerDev** [comment]
> 

For the most part, globbing is a pattern that gives all of the files that end with the ending expression. You are looking for something like os.listdir() in python

**Comment by sryze** [comment]
Thank you, I agree that it possibly could be unexpected behavior for those how are used to APIs in other languages/libraries.

However, given that this library currently supports wildcards being present only in file names and not in parent directory path, i.e. non-recursive matching only, it sort of makes sense to omit the parent directory path. I do see that it woulc be useful to have a full path returned in some situations though.

**Comment by sryze** [comment]
Added an option to receive full paths instead of just file names. Example usage:
```
glob.use_full_paths(true);
```
